# syntax=docker/dockerfile:1.7

FROM node:20-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

FROM base AS build

ARG NEXT_PUBLIC_API_BASE_URL=""
ARG NEXT_PUBLIC_API_TASK_BASE_URL=""
ARG NEXT_PUBLIC_API_CHAT_BASE_URL=""
ARG NEXT_PUBLIC_ENABLE_SW=""
ARG NEXT_PUBLIC_ENABLE_MIDDLEWARE=""
ARG NEXT_PUBLIC_FIREBASE_API_KEY=""
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=""
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID=""
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=""
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=""
ARG NEXT_PUBLIC_FIREBASE_APP_ID=""
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=""
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY=""
ARG NEXT_PUBLIC_CHAT_SOCKET_CONNECT_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_CONNECTED_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_USER_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBED_USER_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_DISCONNECT_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_RECONNECT_DELAY_MS=""
ARG NEXT_PUBLIC_CHAT_SOCKET_PONG_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_ROOM_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_UNSUBSCRIBE_ROOM_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_MESSAGE_SEND_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_USER_QUEUE_ROOM_DEST=""
ARG NEXT_PUBLIC_CHAT_SOCKET_DEBUG=""
ARG NEXT_PUBLIC_CHAT_STOMP_BROKER_URL=""
ARG NEXT_PUBLIC_LIVEKIT_URL=""
ARG API_PROXY_TASK_TARGET=""
ARG API_PROXY_CHAT_TARGET=""
ARG API_PROXY_TARGET=""

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_API_TASK_BASE_URL=${NEXT_PUBLIC_API_TASK_BASE_URL}
ENV NEXT_PUBLIC_API_CHAT_BASE_URL=${NEXT_PUBLIC_API_CHAT_BASE_URL}
ENV NEXT_PUBLIC_ENABLE_SW=${NEXT_PUBLIC_ENABLE_SW}
ENV NEXT_PUBLIC_ENABLE_MIDDLEWARE=${NEXT_PUBLIC_ENABLE_MIDDLEWARE}
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
ENV NEXT_PUBLIC_CHAT_SOCKET_CONNECT_DEST=${NEXT_PUBLIC_CHAT_SOCKET_CONNECT_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_CONNECTED_DEST=${NEXT_PUBLIC_CHAT_SOCKET_CONNECTED_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_USER_DEST=${NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_USER_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBED_USER_DEST=${NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBED_USER_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_DISCONNECT_DEST=${NEXT_PUBLIC_CHAT_SOCKET_DISCONNECT_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_RECONNECT_DELAY_MS=${NEXT_PUBLIC_CHAT_SOCKET_RECONNECT_DELAY_MS}
ENV NEXT_PUBLIC_CHAT_SOCKET_PONG_DEST=${NEXT_PUBLIC_CHAT_SOCKET_PONG_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_ROOM_DEST=${NEXT_PUBLIC_CHAT_SOCKET_SUBSCRIBE_ROOM_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_UNSUBSCRIBE_ROOM_DEST=${NEXT_PUBLIC_CHAT_SOCKET_UNSUBSCRIBE_ROOM_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_MESSAGE_SEND_DEST=${NEXT_PUBLIC_CHAT_SOCKET_MESSAGE_SEND_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_USER_QUEUE_ROOM_DEST=${NEXT_PUBLIC_CHAT_SOCKET_USER_QUEUE_ROOM_DEST}
ENV NEXT_PUBLIC_CHAT_SOCKET_DEBUG=${NEXT_PUBLIC_CHAT_SOCKET_DEBUG}
ENV NEXT_PUBLIC_CHAT_STOMP_BROKER_URL=${NEXT_PUBLIC_CHAT_STOMP_BROKER_URL}
ENV NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
ENV API_PROXY_TASK_TARGET=${API_PROXY_TASK_TARGET}
ENV API_PROXY_CHAT_TARGET=${API_PROXY_CHAT_TARGET}
ENV API_PROXY_TARGET=${API_PROXY_TARGET}
# 환경 변수 주입
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --frozen-lockfile --prefer-offline

COPY . .
RUN --mount=type=cache,id=next-cache,target=/app/.next/cache \
    pnpm build

FROM node:20-slim AS runner

ARG NEXT_PUBLIC_API_TASK_BASE_URL=""
ARG NEXT_PUBLIC_API_CHAT_BASE_URL=""
ARG NEXT_PUBLIC_LIVEKIT_URL=""
ARG API_PROXY_TASK_TARGET=""
ARG API_PROXY_CHAT_TARGET=""
ARG API_PROXY_TARGET=""

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_API_TASK_BASE_URL=${NEXT_PUBLIC_API_TASK_BASE_URL}
ENV NEXT_PUBLIC_API_CHAT_BASE_URL=${NEXT_PUBLIC_API_CHAT_BASE_URL}
ENV NEXT_PUBLIC_LIVEKIT_URL=${NEXT_PUBLIC_LIVEKIT_URL}
ENV API_PROXY_TASK_TARGET=${API_PROXY_TASK_TARGET}
ENV API_PROXY_CHAT_TARGET=${API_PROXY_CHAT_TARGET}
ENV API_PROXY_TARGET=${API_PROXY_TARGET}

WORKDIR /app

COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]
